<a href="https://colab.research.google.com/github/HitanshuGedam/quantum-learning-journey/blob/main/Day9_Tensor_Products_Multi_Qubit_Separability.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Day 9: Tensor Products - Multi-Qubit States, Separability

## From Single Qubits to Composite Systems

## Learning Objectives

By the end of this notebook, you will understand:

1. The tensor product of Hilbert spaces
2. How to construct multi-qubit basis states
3. The difference between separable and entangled states
4. How to represent product states mathematically
5. How to visualize multi-qubit states using QuTiP
6. Criteria for detecting entanglement

## Philosophical Motivation

Single-qubit systems are the building blocks, but the real power of quantum computing emerges when multiple qubits interact. The tensor product provides the mathematical framework for describing composite quantum systems. Understanding the difference between separable (product) states and entangled states is fundamental to quantum information science.


## References

- Nielsen & Chuang (2010). Quantum Computation and Quantum Information. Chapter 2.
- QuTiP Documentation: https://qutip.org/

In [ ]:
# ============================================================================
# SETUP AND INSTALLATIONS
# ============================================================================

!pip install qutip qutip_qip -q

import numpy as np
import qutip as qt
import matplotlib.pyplot as plt

print(f"NumPy version: {np.__version__}")
print(f"QuTiP version: {qt.__version__}")
print("Setup complete.")

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 33.1/33.1 MB 27.0 MB/s eta 0:00:00
NumPy version: 2.0.2
QuTiP version: 5.2.3
Setup complete.


## 1. Tensor Product of Hilbert Spaces

### Definition

The tensor product of two Hilbert spaces $\mathcal{H}_A$ and $\mathcal{H}_B$ is a new Hilbert space $\mathcal{H}_A \otimes \mathcal{H}_B$ with dimension:

$$ \dim(\mathcal{H}_A \otimes \mathcal{H}_B) = \dim(\mathcal{H}_A) \times \dim(\mathcal{H}_B) $$

### For Qubits

For two qubits, each with Hilbert space $\mathbb{C}^2$, the composite space is $\mathbb{C}^2 \otimes \mathbb{C}^2 \cong \mathbb{C}^4$.

### Basis States

The computational basis for two qubits is:

$$ |00\rangle = |0\rangle \otimes |0\rangle = \begin{pmatrix} 1 \\ 0 \\ 0 \\ 0 \end{pmatrix} $$

$$ |01\rangle = |0\rangle \otimes |1\rangle = \begin{pmatrix} 0 \\ 1 \\ 0 \\ 0 \end{pmatrix} $$

$$ |10\rangle = |1\rangle \otimes |0\rangle = \begin{pmatrix} 0 \\ 0 \\ 1 \\ 0 \end{pmatrix} $$

$$ |11\rangle = |1\rangle \otimes |1\rangle = \begin{pmatrix} 0 \\ 0 \\ 0 \\ 1 \end{pmatrix} $$

### Key Properties

<table style="width: 100%; border-collapse: collapse;">
    <thead>
        <tr>
            <th style="text-align: left; padding: 8px; background-color: #f2f2f2;">Property</th>
            <th style="text-align: left; padding: 8px; background-color: #f2f2f2;">Formula</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td style="padding: 8px;">Bilinearity</td>
            <td style="padding: 8px;">$(|\psi_1\rangle + |\psi_2\rangle) \otimes |\phi\rangle = |\psi_1\rangle \otimes |\phi\rangle + |\psi_2\rangle \otimes |\phi\rangle$</td>
        </tr>
        <tr>
            <td style="padding: 8px;">Scalar multiplication</td>
            <td style="padding: 8px;">$(c|\psi\rangle) \otimes |\phi\rangle = c(|\psi\rangle \otimes |\phi\rangle)$</td>
        </tr>
        <tr>
            <td style="padding: 8px;">Inner product</td>
            <td style="padding: 8px;">$\langle\psi_1 \otimes \phi_1 | \psi_2 \otimes \phi_2\rangle = \langle\psi_1|\psi_2\rangle \langle\phi_1|\phi_2\rangle$</td>
        </tr>
    </tbody>
</table>

In [ ]:
# ============================================================================
# CONSTRUCTING MULTI-QUBIT BASIS STATES
# ============================================================================

print("=" * 70)
print("MULTI-QUBIT BASIS STATES")
print("=" * 70)

# Single-qubit basis states
ket0 = qt.basis(2, 0)
ket1 = qt.basis(2, 1)

print("\nSingle-qubit basis states:")
print(f"|0⟩ = {ket0}")
print(f"|1⟩ = {ket1}")

# Create 2-qubit basis states using tensor product
ket00 = qt.tensor(ket0, ket0)
ket01 = qt.tensor(ket0, ket1)
ket10 = qt.tensor(ket1, ket0)
ket11 = qt.tensor(ket1, ket1)

print("\n2-qubit computational basis states:")
print(f"|00⟩ = |0⟩⊗|0⟩ = {ket00}")
print(f"|01⟩ = |0⟩⊗|1⟩ = {ket01}")
print(f"|10⟩ = |1⟩⊗|0⟩ = {ket10}")
print(f"|11⟩ = |1⟩⊗|1⟩ = {ket11}")

# Create a product state |+⟩|0⟩
ket_plus = (ket0 + ket1).unit()
product_state = qt.tensor(ket_plus, ket0)

print(f"\nProduct state |+⟩|0⟩ = {product_state}")

# Verify the dimension
print(f"\nDimension of 2-qubit space: {ket00.shape[0]}")
print(f"Expected: 2² = 4")

MULTI-QUBIT BASIS STATES

Single-qubit basis states:
|0⟩ = Quantum object: dims=[[2], [1]], shape=(2, 1), type='ket', dtype=Dense
Qobj data =
[[1.]
 [0.]]
|1⟩ = Quantum object: dims=[[2], [1]], shape=(2, 1), type='ket', dtype=Dense
Qobj data =
[[0.]
 [1.]]

2-qubit computational basis states:
|00⟩ = |0⟩⊗|0⟩ = Quantum object: dims=[[2, 2], [1]], shape=(4, 1), type='ket', dtype=Dense
Qobj data =
[[1.]
 [0.]
 [0.]
 [0.]]
|01⟩ = |0⟩⊗|1⟩ = Quantum object: dims=[[2, 2], [1]], shape=(4, 1), type='ket', dtype=Dense
Qobj data =
[[0.]
 [1.]
 [0.]
 [0.]]
|10⟩ = |1⟩⊗|0⟩ = Quantum object: dims=[[2, 2], [1]], shape=(4, 1), type='ket', dtype=Dense
Qobj data =
[[0.]
 [0.]
 [1.]
 [0.]]
|11⟩ = |1⟩⊗|1⟩ = Quantum object: dims=[[2, 2], [1]], shape=(4, 1), type='ket', dtype=Dense
Qobj data =
[[0.]
 [0.]
 [0.]
 [1.]]

Product state |+⟩|0⟩ = Quantum object: dims=[[2, 2], [1]], shape=(4, 1), type='ket', dtype=Dense
Qobj data =
[[0.70710678]
 [0.        ]
 [0.70710678]
 [0.        ]]

Dimension of 2-qubit space

## 2. General Multi-Qubit States

### Superposition in Composite Systems

Any 2-qubit state can be written as:

$$ |\psi\rangle = \alpha_{00}|00\rangle + \alpha_{01}|01\rangle + \alpha_{10}|10\rangle + \alpha_{11}|11\rangle $$

with normalization condition:

$$ |\alpha_{00}|^2 + |\alpha_{01}|^2 + |\alpha_{10}|^2 + |\alpha_{11}|^2 = 1 $$

### Separable (Product) States

A state is **separable** (product state) if it can be written as:

$$ |\psi\rangle = |\psi_A\rangle \otimes |\psi_B\rangle $$

### Entangled States

A state is **entangled** if it cannot be written as a product state.

### Examples

<table style="width: 100%; border-collapse: collapse;">
    <thead>
        <tr>
            <th style="text-align: left; padding: 8px; background-color: #f2f2f2;">State Type</th>
            <th style="text-align: left; padding: 8px; background-color: #f2f2f2;">Example</th>
            <th style="text-align: left; padding: 8px; background-color: #f2f2f2;">Separable?</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td style="padding: 8px;">Product</td>
            <td style="padding: 8px;">$|0\rangle \otimes |1\rangle = |01\rangle$</td>
            <td style="padding: 8px;">Yes</td>
        </tr>
        <tr>
            <td style="padding: 8px;">Product</td>
            <td style="padding: 8px;">$|+\rangle \otimes |+\rangle = \frac{1}{2}(|00\rangle + |01\rangle + |10\rangle + |11\rangle)$</td>
            <td style="padding: 8px;">Yes</td>
        </tr>
        <tr>
            <td style="padding: 8px;">Entangled</td>
            <td style="padding: 8px;">$\frac{|00\rangle + |11\rangle}{\sqrt{2}}$</td>
            <td style="padding: 8px;">No</td>
        </tr>
        <tr>
            <td style="padding: 8px;">Entangled</td>
            <td style="padding: 8px;">$\frac{|01\rangle + |10\rangle}{\sqrt{2}}$</td>
            <td style="padding: 8px;">No</td>
        </tr>
    </tbody>
</table>

In [ ]:
# ============================================================================
# CREATING AND IDENTIFYING SEPARABLE VS ENTANGLED STATES
# ============================================================================

print("=" * 70)
print("SEPARABLE VS ENTANGLED STATES")
print("=" * 70)

# Single-qubit states
ket0 = qt.basis(2, 0)
ket1 = qt.basis(2, 1)
ket_plus = (ket0 + ket1).unit()
ket_minus = (ket0 - ket1).unit()

# Create separable (product) states
product_state1 = qt.tensor(ket0, ket0)  # |00⟩
product_state2 = qt.tensor(ket_plus, ket_plus)  # |+⟩|+⟩

print("\nSeparable (Product) States:")
print(f"|00⟩ = {product_state1}")
print(f"|+⟩|+⟩ = {product_state2}")

# Create entangled states (Bell states)
bell_phi_plus = (qt.tensor(ket0, ket0) + qt.tensor(ket1, ket1)).unit()
bell_psi_plus = (qt.tensor(ket0, ket1) + qt.tensor(ket1, ket0)).unit()

print("\nEntangled States (Bell States):")
print(f"|Φ⁺⟩ = (|00⟩ + |11⟩)/√2 = {bell_phi_plus}")
print(f"|Ψ⁺⟩ = (|01⟩ + |10⟩)/√2 = {bell_psi_plus}")

# Verify that product states can be factored
print("\nVerifying separability:")
print(f"|00⟩ = |0⟩⊗|0⟩? {np.allclose(product_state1.full(), qt.tensor(ket0, ket0).full())}")

# Check if a state is entangled by trying to factor it
def is_product_state(state, tol=1e-10):
    """Check if a 2-qubit state is a product state."""
    # Reshape the state into a matrix
    state_mat = state.full().reshape(2, 2)
    # Check if the matrix has rank 1
    rank = np.linalg.matrix_rank(state_mat, tol=tol)
    return rank == 1

print(f"\nIs |00⟩ a product state? {is_product_state(product_state1)}")
print(f"Is |+⟩|+⟩ a product state? {is_product_state(product_state2)}")
print(f"Is |Φ⁺⟩ a product state? {is_product_state(bell_phi_plus)}")
print(f"Is |Ψ⁺⟩ a product state? {is_product_state(bell_psi_plus)}")

SEPARABLE VS ENTANGLED STATES

Separable (Product) States:
|00⟩ = Quantum object: dims=[[2, 2], [1]], shape=(4, 1), type='ket', dtype=Dense
Qobj data =
[[1.]
 [0.]
 [0.]
 [0.]]
|+⟩|+⟩ = Quantum object: dims=[[2, 2], [1]], shape=(4, 1), type='ket', dtype=Dense
Qobj data =
[[0.5]
 [0.5]
 [0.5]
 [0.5]]

Entangled States (Bell States):
|Φ⁺⟩ = (|00⟩ + |11⟩)/√2 = Quantum object: dims=[[2, 2], [1]], shape=(4, 1), type='ket', dtype=Dense
Qobj data =
[[0.70710678]
 [0.        ]
 [0.        ]
 [0.70710678]]
|Ψ⁺⟩ = (|01⟩ + |10⟩)/√2 = Quantum object: dims=[[2, 2], [1]], shape=(4, 1), type='ket', dtype=Dense
Qobj data =
[[0.        ]
 [0.70710678]
 [0.70710678]
 [0.        ]]

Verifying separability:
|00⟩ = |0⟩⊗|0⟩? True

Is |00⟩ a product state? True
Is |+⟩|+⟩ a product state? True
Is |Φ⁺⟩ a product state? False
Is |Ψ⁺⟩ a product state? False


## 3. Tensor Product of Operators

### Definition

The tensor product of operators $A$ on $\mathcal{H}_A$ and $B$ on $\mathcal{H}_B$ acts on product states as:

$$ (A \otimes B)(|\psi\rangle \otimes |\phi\rangle) = (A|\psi\rangle) \otimes (B|\phi\rangle) $$

### Matrix Representation

For $2 \times 2$ matrices, the Kronecker product gives the $4 \times 4$ matrix:

$$ A \otimes B = \begin{pmatrix} a_{11}B & a_{12}B \\ a_{21}B & a_{22}B \end{pmatrix} $$

### Examples

<table style="width: 100%; border-collapse: collapse;">
    <thead>
        <tr>
            <th style="text-align: left; padding: 8px; background-color: #f2f2f2;">Operator on Qubit A</th>
            <th style="text-align: left; padding: 8px; background-color: #f2f2f2;">Operator on Qubit B</th>
            <th style="text-align: left; padding: 8px; background-color: #f2f2f2;">Composite Operator</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td style="padding: 8px;">$X$</td>
            <td style="padding: 8px;">$I$</td>
            <td style="padding: 8px;">$X \otimes I$</td>
        </tr>
        <tr>
            <td style="padding: 8px;">$I$</td>
            <td style="padding: 8px;">$Y$</td>
            <td style="padding: 8px;">$I \otimes Y$</td>
        </tr>
        <tr>
            <td style="padding: 8px;">$Z$</td>
            <td style="padding: 8px;">$Z$</td>
            <td style="padding: 8px;">$Z \otimes Z$</td>
        </tr>
    </tbody>
</table>

### Controlled Gates

The CNOT gate can be expressed as:

$$ \text{CNOT} = |0\rangle\langle0| \otimes I + |1\rangle\langle1| \otimes X $$

In [ ]:
# ============================================================================
# TENSOR PRODUCT OF OPERATORS
# ============================================================================

print("=" * 70)
print("TENSOR PRODUCT OF OPERATORS")
print("=" * 70)

# Single-qubit operators
I = qt.qeye(2)
X = qt.sigmax()
Y = qt.sigmay()
Z = qt.sigmaz()

# Tensor product operators
X_I = qt.tensor(X, I)
I_X = qt.tensor(I, X)
Z_Z = qt.tensor(Z, Z)

print("\nTensor product operators:")
print(f"X ⊗ I =")
print(X_I)
print(f"\nI ⊗ X =")
print(I_X)
print(f"\nZ ⊗ Z =")
print(Z_Z)

# Apply operators to states
ket00 = qt.tensor(qt.basis(2, 0), qt.basis(2, 0))
ket01 = qt.tensor(qt.basis(2, 0), qt.basis(2, 1))

print(f"\nApplying X ⊗ I on |00⟩:")
print(f"(X ⊗ I)|00⟩ = {X_I * ket00}")
print(f"Expected: |10⟩ = {qt.tensor(qt.basis(2, 1), qt.basis(2, 0))}")

print(f"\nApplying I ⊗ X on |00⟩:")
print(f"(I ⊗ X)|00⟩ = {I_X * ket00}")
print(f"Expected: |01⟩ = {qt.tensor(qt.basis(2, 0), qt.basis(2, 1))}")

# CNOT gate construction
P0 = qt.basis(2, 0) * qt.basis(2, 0).dag()
P1 = qt.basis(2, 1) * qt.basis(2, 1).dag()
CNOT = qt.tensor(P0, I) + qt.tensor(P1, X)

print(f"\nCNOT gate constructed from tensor products:")
print(CNOT)

TENSOR PRODUCT OF OPERATORS

Tensor product operators:
X ⊗ I =
Quantum object: dims=[[2, 2], [2, 2]], shape=(4, 4), type='oper', dtype=CSR, isherm=True
Qobj data =
[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]

I ⊗ X =
Quantum object: dims=[[2, 2], [2, 2]], shape=(4, 4), type='oper', dtype=CSR, isherm=True
Qobj data =
[[0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]]

Z ⊗ Z =
Quantum object: dims=[[2, 2], [2, 2]], shape=(4, 4), type='oper', dtype=CSR, isherm=True
Qobj data =
[[ 1.  0.  0.  0.]
 [ 0. -1.  0.  0.]
 [ 0.  0. -1.  0.]
 [ 0.  0.  0.  1.]]

Applying X ⊗ I on |00⟩:
(X ⊗ I)|00⟩ = Quantum object: dims=[[2, 2], [1]], shape=(4, 1), type='ket', dtype=Dense
Qobj data =
[[0.]
 [0.]
 [1.]
 [0.]]
Expected: |10⟩ = Quantum object: dims=[[2, 2], [1]], shape=(4, 1), type='ket', dtype=Dense
Qobj data =
[[0.]
 [0.]
 [1.]
 [0.]]

Applying I ⊗ X on |00⟩:
(I ⊗ X)|00⟩ = Quantum object: dims=[[2, 2], [1]], shape=(4, 1), type='ket', dtype=Dense
Qobj data =
[[0.]
 [1.]
 [

## 4. Partial Trace and Reduced Density Matrices

### Definition

For a bipartite state $\rho_{AB}$, the reduced density matrix for subsystem $A$ is:

$$ \rho_A = \text{Tr}_B(\rho_{AB}) $$

where $\text{Tr}_B$ denotes the partial trace over subsystem $B$.

### For Product States

If $\rho_{AB} = \rho_A \otimes \rho_B$, then:

$$ \text{Tr}_B(\rho_{AB}) = \rho_A \cdot \text{Tr}(\rho_B) = \rho_A $$

### For Entangled States

For a Bell state, the reduced states are maximally mixed:

$$ \rho_A = \text{Tr}_B(|\Phi^+\rangle\langle\Phi^+|) = \frac{I}{2} $$

### Key Insight

<table style="width: 100%; border-collapse: collapse;">
    <thead>
        <tr>
            <th style="text-align: left; padding: 8px; background-color: #f2f2f2;">State Type</th>
            <th style="text-align: left; padding: 8px; background-color: #f2f2f2;">Global State Purity</th>
            <th style="text-align: left; padding: 8px; background-color: #f2f2f2;">Reduced State Purity</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td style="padding: 8px;">Separable</td>
            <td style="padding: 8px;">1 (if pure)</td>
            <td style="padding: 8px;">1 (pure)</td>
        </tr>
        <tr>
            <td style="padding: 8px;">Entangled</td>
            <td style="padding: 8px;">1 (pure)</td>
            <td style="padding: 8px;">Less than 1 (mixed)</td>
        </tr>
    </tbody>
</table>

In [ ]:
# ============================================================================
# PARTIAL TRACE AND REDUCED DENSITY MATRICES
# ============================================================================

print("=" * 70)
print("PARTIAL TRACE AND REDUCED DENSITY MATRICES")
print("=" * 70)

# Create a product state
ket0 = qt.basis(2, 0)
ket1 = qt.basis(2, 1)
product_ket = qt.tensor(ket0, ket0)
rho_product = product_ket * product_ket.dag()

# Create an entangled state (Bell state)
bell_ket = (qt.tensor(ket0, ket0) + qt.tensor(ket1, ket1)).unit()
rho_bell = bell_ket * bell_ket.dag()

print("\nProduct state |00⟩⟨00|:")
print(f"ρ_product = {rho_product}")

print("\nEntangled state |Φ⁺⟩⟨Φ⁺|:")
print(f"ρ_bell = {rho_bell}")

# Compute reduced density matrices
rho_product_A = rho_product.ptrace(0)
rho_product_B = rho_product.ptrace(1)
rho_bell_A = rho_bell.ptrace(0)
rho_bell_B = rho_bell.ptrace(1)

print("\nReduced density matrices for product state:")
print(f"ρ_A = {rho_product_A}")
print(f"ρ_B = {rho_product_B}")
print(f"ρ_A is pure? {np.allclose((rho_product_A * rho_product_A).tr().real, 1.0)}")

print("\nReduced density matrices for Bell state:")
print(f"ρ_A = {rho_bell_A}")
print(f"ρ_B = {rho_bell_B}")
print(f"ρ_A is maximally mixed? {np.allclose(rho_bell_A.full(), qt.qeye(2).full() / 2)}")
print(f"ρ_A purity: {(rho_bell_A * rho_bell_A).tr().real:.3f}")

# Verify the partial trace property
print("\nVerifying: Tr(ρ_A) = Tr(ρ_AB)")
print(f"Tr(ρ_AB) = {rho_bell.tr():.1f}")
print(f"Tr(ρ_A) = {rho_bell_A.tr():.1f}")
print(f"Tr(ρ_B) = {rho_bell_B.tr():.1f}")

PARTIAL TRACE AND REDUCED DENSITY MATRICES

Product state |00⟩⟨00|:
ρ_product = Quantum object: dims=[[2, 2], [2, 2]], shape=(4, 4), type='oper', dtype=CSR, isherm=True
Qobj data =
[[1. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Entangled state |Φ⁺⟩⟨Φ⁺|:
ρ_bell = Quantum object: dims=[[2, 2], [2, 2]], shape=(4, 4), type='oper', dtype=CSR, isherm=True
Qobj data =
[[0.5 0.  0.  0.5]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.5 0.  0.  0.5]]

Reduced density matrices for product state:
ρ_A = Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=CSR, isherm=True
Qobj data =
[[1. 0.]
 [0. 0.]]
ρ_B = Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=CSR, isherm=True
Qobj data =
[[1. 0.]
 [0. 0.]]
ρ_A is pure? True

Reduced density matrices for Bell state:
ρ_A = Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=CSR, isherm=True
Qobj data =
[[0.5 0. ]
 [0.  0.5]]
ρ_B = Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=CSR

## 5. Schmidt Decomposition

### Theorem

Any pure bipartite state $|\psi\rangle \in \mathcal{H}_A \otimes \mathcal{H}_B$ can be written as:

$$ |\psi\rangle = \sum_{i=1}^{r} \lambda_i |i_A\rangle |i_B\rangle $$

where $\lambda_i > 0$ are the **Schmidt coefficients** and $r$ is the **Schmidt rank**.

### Properties

<table style="width: 100%; border-collapse: collapse;">
    <thead>
        <tr>
            <th style="text-align: left; padding: 8px; background-color: #f2f2f2;">Property</th>
            <th style="text-align: left; padding: 8px; background-color: #f2f2f2;">Description</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td style="padding: 8px;">Normalization</td>
            <td style="padding: 8px;">$\sum_i \lambda_i^2 = 1$</td>
        </tr>
        <tr>
            <td style="padding: 8px;">Schmidt rank = 1</td>
            <td style="padding: 8px;">Product (separable) state</td>
        </tr>
        <tr>
            <td style="padding: 8px;">Schmidt rank > 1</td>
            <td style="padding: 8px;">Entangled state</td>
        </tr>
        <tr>
            <td style="padding: 8px;">All $\lambda_i$ equal</td>
            <td style="padding: 8px;">Maximally entangled</td>
        </tr>
    </tbody>
</table>

### For 2-Qubit States

The Schmidt decomposition takes the form:

$$ |\psi\rangle = \lambda_1 |u_1\rangle|v_1\rangle + \lambda_2 |u_2\rangle|v_2\rangle $$

where $\lambda_1^2 + \lambda_2^2 = 1$.

In [ ]:
# ============================================================================
# SCHMIDT DECOMPOSITION
# ============================================================================

print("=" * 70)
print("SCHMIDT DECOMPOSITION")
print("=" * 70)

def schmidt_decomposition(psi):
    """Compute Schmidt coefficients for a 2-qubit state."""
    # Reshape the state into a matrix
    psi_mat = psi.full().reshape(2, 2)
    # Compute singular value decomposition
    U, s, Vh = np.linalg.svd(psi_mat)
    return s  # Schmidt coefficients

# Create different types of states
ket0 = qt.basis(2, 0)
ket1 = qt.basis(2, 1)

# Product state
product_ket = qt.tensor(ket0, ket0)

# Partially entangled state
theta = np.pi/6
partial_ket = np.cos(theta) * qt.tensor(ket0, ket0) + np.sin(theta) * qt.tensor(ket1, ket1)
partial_ket = partial_ket.unit()

# Maximally entangled state (Bell state)
bell_ket = (qt.tensor(ket0, ket0) + qt.tensor(ket1, ket1)).unit()

states = [
    ("Product |00⟩", product_ket),
    ("Partially entangled", partial_ket),
    ("Maximally entangled |Φ⁺⟩", bell_ket)
]

print("\nSchmidt coefficients for different states:")
print("-" * 60)

for name, state in states:
    coeffs = schmidt_decomposition(state)
    print(f"\n{name}:")
    print(f"  Schmidt coefficients: {coeffs[0]:.4f}, {coeffs[1]:.4f}")
    print(f"  Schmidt rank: {np.sum(coeffs > 1e-10)}")
    print(f"  Entanglement measure (concurrence): {2 * coeffs[0] * coeffs[1]:.4f}")

SCHMIDT DECOMPOSITION

Schmidt coefficients for different states:
------------------------------------------------------------

Product |00⟩:
  Schmidt coefficients: 1.0000, 0.0000
  Schmidt rank: 1
  Entanglement measure (concurrence): 0.0000

Partially entangled:
  Schmidt coefficients: 0.8660, 0.5000
  Schmidt rank: 2
  Entanglement measure (concurrence): 0.8660

Maximally entangled |Φ⁺⟩:
  Schmidt coefficients: 0.7071, 0.7071
  Schmidt rank: 2
  Entanglement measure (concurrence): 1.0000


## 6. Summary and Key Insights


### Key Formulas

$$ \mathcal{H}_{AB} = \mathcal{H}_A \otimes \mathcal{H}_B $$

$$ |ij\rangle = |i\rangle \otimes |j\rangle $$

$$ |\psi\rangle = |\psi_A\rangle \otimes |\psi_B\rangle $$

$$ (A \otimes B)(|\psi\rangle \otimes |\phi\rangle) = A|\psi\rangle \otimes B|\phi\rangle $$

$$ \rho_A = \text{Tr}_B(\rho_{AB}) $$

### Separability Criteria

<table style="width: 100%; border-collapse: collapse;">
    <thead>
        <tr>
            <th style="text-align: left; padding: 8px; background-color: #f2f2f2;">Test</th>
            <th style="text-align: left; padding: 8px; background-color: #f2f2f2;">Product State</th>
            <th style="text-align: left; padding: 8px; background-color: #f2f2f2;">Entangled State</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td style="padding: 8px;">Schmidt rank</td>
            <td style="padding: 8px;">1</td>
            <td style="padding: 8px;">> 1</td>
        </tr>
        <tr>
            <td style="padding: 8px;">Reduced state purity (global pure)</td>
            <td style="padding: 8px;">1</td>
            <td style="padding: 8px;">&lt; 1</td>
        </tr>
        <tr>
            <td style="padding: 8px;">Can be factored</td>
            <td style="padding: 8px;">Yes</td>
            <td style="padding: 8px;">No</td>
        </tr>
    </tbody>
</table>

### Key Takeaways

1. **Tensor product** combines Hilbert spaces of multiple qubits
2. **Separable states** can be written as product of individual states
3. **Entangled states** cannot be written as product states
4. **Schmidt decomposition** provides a canonical form for bipartite states
5. **Partial trace** gives the state of a subsystem
6. **Reduced density matrices** of entangled states are mixed

---

**Day 9 Complete!** 🎉

You now understand:
- The tensor product of Hilbert spaces
- How to construct multi-qubit basis states
- The difference between separable and entangled states
- How to represent product states mathematically
- How to compute partial traces and reduced density matrices
- The Schmidt decomposition and its applications

Proceed to Day 10 when ready.