<a href="https://colab.research.google.com/github/HitanshuGedam/quantum-learning-journey/blob/main/Day10_Tensor_Product_Gates.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Day 10: Multi-Qubit Gates via Tensor Products

## Building Composite Gates from Single-Qubit Operations

## Learning Objectives

By the end of this notebook, you will understand:

1. How to construct multi-qubit gates using tensor products
2. The difference between $X \otimes I$, $I \otimes X$, $X \otimes X$, and $Z \otimes Z$
3. How to apply gates to specific qubits in a multi-qubit system
4. The mathematical structure of $H \otimes H$ and its action on product states
5. How to visualize multi-qubit gate operations using QuTiP

## Technical Depth

- Tensor product of Pauli operators
- Action on computational basis states
- Matrix representations ($4 \times 4$)
- Separable vs entangling gates
- Kronecker product calculations

## References

- Nielsen & Chuang (2010). Quantum Computation and Quantum Information. Chapter 2.
- QuTiP Documentation: https://qutip.org/

In [1]:
# ============================================================================
# SETUP AND INSTALLATIONS
# ============================================================================

!pip install qutip qutip_qip -q

import numpy as np
import qutip as qt
import matplotlib.pyplot as plt

print(f"NumPy version: {np.__version__}")
print(f"QuTiP version: {qt.__version__}")
print("Setup complete.")

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 33.1/33.1 MB 26.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.8/140.8 kB 3.9 MB/s eta 0:00:00
NumPy version: 2.0.2
QuTiP version: 5.2.3
Setup complete.


## 1. Tensor Product of Single-Qubit Gates

### Definition

For single-qubit operators $A$ and $B$, the composite operator acting on a two-qubit system is:

$$ A \otimes B $$

When applied to a product state:

$$ (A \otimes B)(|\psi\rangle \otimes |\phi\rangle) = (A|\psi\rangle) \otimes (B|\phi\rangle) $$

### Matrix Representation

For $2 \times 2$ matrices, the Kronecker product gives a $4 \times 4$ matrix:

$$ A \otimes B = \begin{pmatrix} a_{11}B & a_{12}B \\ a_{21}B & a_{22}B \end{pmatrix} $$

### Important Composite Gates

<table style="width: 100%; border-collapse: collapse;">
    <thead>
        <tr>
            <th style="text-align: left; padding: 8px; background-color: #f2f2f2;">Gate</th>
            <th style="text-align: left; padding: 8px; background-color: #f2f2f2;">Mathematical Form</th>
            <th style="text-align: left; padding: 8px; background-color: #f2f2f2;">Action</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td style="padding: 8px;">$X \otimes I$</td>
            <td style="padding: 8px;">$X$ on qubit A, identity on qubit B</td>
            <td style="padding: 8px;">Flips first qubit</td>
        </tr>
        <tr>
            <td style="padding: 8px;">$I \otimes X$</td>
            <td style="padding: 8px;">Identity on qubit A, $X$ on qubit B</td>
            <td style="padding: 8px;">Flips second qubit</td>
        </tr>
        <tr>
            <td style="padding: 8px;">$X \otimes X$</td>
            <td style="padding: 8px;">$X$ on both qubits</td>
            <td style="padding: 8px;">Flips both qubits</td>
        </tr>
        <tr>
            <td style="padding: 8px;">$Z \otimes Z$</td>
            <td style="padding: 8px;">$Z$ on both qubits</td>
            <td style="padding: 8px;">Phase flip on both qubits</td>
        </tr>
        <tr>
            <td style="padding: 8px;">$H \otimes H$</td>
            <td style="padding: 8px;">Hadamard on both qubits</td>
            <td style="padding: 8px;">Creates superposition on both</td>
        </tr>
    </tbody>
</table>

### Key Insight

- **Single-qubit gates** applied to specific qubits use $I$ on the other qubits
- Example: Apply $X$ to first qubit only → $X \otimes I$
- Example: Apply $H$ to second qubit only → $I \otimes H$

In [2]:
# ============================================================================
# TENSOR PRODUCT GATES: X ⊗ I, I ⊗ X, X ⊗ X, Z ⊗ Z
# ============================================================================

print("=" * 70)
print("TENSOR PRODUCT GATES")
print("=" * 70)

# Single-qubit gates
I = qt.qeye(2)
X = qt.sigmax()
Z = qt.sigmaz()
H = (1 / np.sqrt(2)) * (qt.sigmax() + qt.sigmaz())

# Two-qubit composite gates
X_I = qt.tensor(X, I)
I_X = qt.tensor(I, X)
X_X = qt.tensor(X, X)
Z_Z = qt.tensor(Z, Z)
H_H = qt.tensor(H, H)

print("\nComposite gates:")
print(f"X ⊗ I =\n{X_I}")
print(f"\nI ⊗ X =\n{I_X}")
print(f"\nX ⊗ X =\n{X_X}")
print(f"\nZ ⊗ Z =\n{Z_Z}")
print(f"\nH ⊗ H =\n{H_H}")

# Verify dimensions
print(f"\nDimensions: {X_I.shape[0]} × {X_I.shape[1]} (expected: 4×4)")

TENSOR PRODUCT GATES

Composite gates:
X ⊗ I =
Quantum object: dims=[[2, 2], [2, 2]], shape=(4, 4), type='oper', dtype=CSR, isherm=True
Qobj data =
[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]

I ⊗ X =
Quantum object: dims=[[2, 2], [2, 2]], shape=(4, 4), type='oper', dtype=CSR, isherm=True
Qobj data =
[[0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]]

X ⊗ X =
Quantum object: dims=[[2, 2], [2, 2]], shape=(4, 4), type='oper', dtype=CSR, isherm=True
Qobj data =
[[0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]]

Z ⊗ Z =
Quantum object: dims=[[2, 2], [2, 2]], shape=(4, 4), type='oper', dtype=CSR, isherm=True
Qobj data =
[[ 1.  0.  0.  0.]
 [ 0. -1.  0.  0.]
 [ 0.  0. -1.  0.]
 [ 0.  0.  0.  1.]]

H ⊗ H =
Quantum object: dims=[[2, 2], [2, 2]], shape=(4, 4), type='oper', dtype=CSR, isherm=True
Qobj data =
[[ 0.5  0.5  0.5  0.5]
 [ 0.5 -0.5  0.5 -0.5]
 [ 0.5  0.5 -0.5 -0.5]
 [ 0.5 -0.5 -0.5  0.5]]

Dimensions: 4 × 4 (expected: 4×4)


## 2. Action on Computational Basis States

### Basis States

The two-qubit computational basis is:

$$ |00\rangle, |01\rangle, |10\rangle, |11\rangle $$

### Applying $X \otimes I$

<table style="width: 100%; border-collapse: collapse;">
    <thead>
        <tr>
            <th style="text-align: left; padding: 8px; background-color: #f2f2f2;">Input</th>
            <th style="text-align: left; padding: 8px; background-color: #f2f2f2;">Output</th>
            <th style="text-align: left; padding: 8px; background-color: #f2f2f2;">Explanation</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td style="padding: 8px;">$|00\rangle$</td>
            <td style="padding: 8px;">$|10\rangle$</td>
            <td style="padding: 8px;">X flips first qubit</td>
        </tr>
        <tr>
            <td style="padding: 8px;">$|01\rangle$</td>
            <td style="padding: 8px;">$|11\rangle$</td>
            <td style="padding: 8px;">X flips first qubit</td>
        </tr>
        <tr>
            <td style="padding: 8px;">$|10\rangle$</td>
            <td style="padding: 8px;">$|00\rangle$</td>
            <td style="padding: 8px;">X flips first qubit</td>
        </tr>
        <tr>
            <td style="padding: 8px;">$|11\rangle$</td>
            <td style="padding: 8px;">$|01\rangle$</td>
            <td style="padding: 8px;">X flips first qubit</td>
        </tr>
    </tbody>
</table>

### Applying $I \otimes X$

<table style="width: 100%; border-collapse: collapse;">
    <thead>
        <tr>
            <th style="text-align: left; padding: 8px; background-color: #f2f2f2;">Input</th>
            <th style="text-align: left; padding: 8px; background-color: #f2f2f2;">Output</th>
            <th style="text-align: left; padding: 8px; background-color: #f2f2f2;">Explanation</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td style="padding: 8px;">$|00\rangle$</td>
            <td style="padding: 8px;">$|01\rangle$</td>
            <td style="padding: 8px;">X flips second qubit</td>
        </tr>
        <tr>
            <td style="padding: 8px;">$|01\rangle$</td>
            <td style="padding: 8px;">$|00\rangle$</td>
            <td style="padding: 8px;">X flips second qubit</td>
        </tr>
        <tr>
            <td style="padding: 8px;">$|10\rangle$</td>
            <td style="padding: 8px;">$|11\rangle$</td>
            <td style="padding: 8px;">X flips second qubit</td>
        </tr>
        <tr>
            <td style="padding: 8px;">$|11\rangle$</td>
            <td style="padding: 8px;">$|10\rangle$</td>
            <td style="padding: 8px;">X flips second qubit</td>
        </tr>
    </tbody>
</table>

### Applying $X \otimes X$

<table style="width: 100%; border-collapse: collapse;">
    <thead>
        <tr>
            <th style="text-align: left; padding: 8px; background-color: #f2f2f2;">Input</th>
            <th style="text-align: left; padding: 8px; background-color: #f2f2f2;">Output</th>
            <th style="text-align: left; padding: 8px; background-color: #f2f2f2;">Explanation</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td style="padding: 8px;">$|00\rangle$</td>
            <td style="padding: 8px;">$|11\rangle$</td>
            <td style="padding: 8px;">Both qubits flip</td>
        </tr>
        <tr>
            <td style="padding: 8px;">$|01\rangle$</td>
            <td style="padding: 8px;">$|10\rangle$</td>
            <td style="padding: 8px;">Both qubits flip</td>
        </tr>
        <tr>
            <td style="padding: 8px;">$|10\rangle$</td>
            <td style="padding: 8px;">$|01\rangle$</td>
            <td style="padding: 8px;">Both qubits flip</td>
        </tr>
        <tr>
            <td style="padding: 8px;">$|11\rangle$</td>
            <td style="padding: 8px;">$|00\rangle$</td>
            <td style="padding: 8px;">Both qubits flip</td>
        </tr>
    </tbody>
</table>

### Applying $Z \otimes Z$

<table style="width: 100%; border-collapse: collapse;">
    <thead>
        <tr>
            <th style="text-align: left; padding: 8px; background-color: #f2f2f2;">Input</th>
            <th style="text-align: left; padding: 8px; background-color: #f2f2f2;">Output</th>
            <th style="text-align: left; padding: 8px; background-color: #f2f2f2;">Explanation</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td style="padding: 8px;">$|00\rangle$</td>
            <td style="padding: 8px;">$|00\rangle$</td>
            <td style="padding: 8px;">$Z|0\rangle = |0\rangle$</td>
        </tr>
        <tr>
            <td style="padding: 8px;">$|01\rangle$</td>
            <td style="padding: 8px;">$-|01\rangle$</td>
            <td style="padding: 8px;">$Z|1\rangle = -|1\rangle$</td>
        </tr>
        <tr>
            <td style="padding: 8px;">$|10\rangle$</td>
            <td style="padding: 8px;">$-|10\rangle$</td>
            <td style="padding: 8px;">$Z|1\rangle = -|1\rangle$</td>
        </tr>
        <tr>
            <td style="padding: 8px;">$|11\rangle$</td>
            <td style="padding: 8px;">$|11\rangle$</td>
            <td style="padding: 8px;">$Z|1\rangle \otimes Z|1\rangle = (-1)(-1)|11\rangle = +|11\rangle$</td>
        </tr>
    </tbody>
</table>

In [3]:
# ============================================================================
# VERIFYING GATE ACTIONS ON BASIS STATES
# ============================================================================

print("=" * 70)
print("VERIFYING GATE ACTIONS ON BASIS STATES")
print("=" * 70)

# Create basis states
ket0 = qt.basis(2, 0)
ket1 = qt.basis(2, 1)

ket00 = qt.tensor(ket0, ket0)
ket01 = qt.tensor(ket0, ket1)
ket10 = qt.tensor(ket1, ket0)
ket11 = qt.tensor(ket1, ket1)

basis_states = [("|00⟩", ket00), ("|01⟩", ket01), ("|10⟩", ket10), ("|11⟩", ket11)]

# Define gates
I = qt.qeye(2)
X = qt.sigmax()
Z = qt.sigmaz()

X_I = qt.tensor(X, I)
I_X = qt.tensor(I, X)
X_X = qt.tensor(X, X)
Z_Z = qt.tensor(Z, Z)

print("\n" + "=" * 50)
print("X ⊗ I ACTIONS")
print("=" * 50)

for name, state in basis_states:
    result = X_I * state
    print(f"(X ⊗ I){name} = {result}")

print("\n" + "=" * 50)
print("I ⊗ X ACTIONS")
print("=" * 50)

for name, state in basis_states:
    result = I_X * state
    print(f"(I ⊗ X){name} = {result}")

print("\n" + "=" * 50)
print("X ⊗ X ACTIONS")
print("=" * 50)

for name, state in basis_states:
    result = X_X * state
    print(f"(X ⊗ X){name} = {result}")

print("\n" + "=" * 50)
print("Z ⊗ Z ACTIONS")
print("=" * 50)

for name, state in basis_states:
    result = Z_Z * state
    print(f"(Z ⊗ Z){name} = {result}")

VERIFYING GATE ACTIONS ON BASIS STATES

X ⊗ I ACTIONS
(X ⊗ I)|00⟩ = Quantum object: dims=[[2, 2], [1]], shape=(4, 1), type='ket', dtype=Dense
Qobj data =
[[0.]
 [0.]
 [1.]
 [0.]]
(X ⊗ I)|01⟩ = Quantum object: dims=[[2, 2], [1]], shape=(4, 1), type='ket', dtype=Dense
Qobj data =
[[0.]
 [0.]
 [0.]
 [1.]]
(X ⊗ I)|10⟩ = Quantum object: dims=[[2, 2], [1]], shape=(4, 1), type='ket', dtype=Dense
Qobj data =
[[1.]
 [0.]
 [0.]
 [0.]]
(X ⊗ I)|11⟩ = Quantum object: dims=[[2, 2], [1]], shape=(4, 1), type='ket', dtype=Dense
Qobj data =
[[0.]
 [1.]
 [0.]
 [0.]]

I ⊗ X ACTIONS
(I ⊗ X)|00⟩ = Quantum object: dims=[[2, 2], [1]], shape=(4, 1), type='ket', dtype=Dense
Qobj data =
[[0.]
 [1.]
 [0.]
 [0.]]
(I ⊗ X)|01⟩ = Quantum object: dims=[[2, 2], [1]], shape=(4, 1), type='ket', dtype=Dense
Qobj data =
[[1.]
 [0.]
 [0.]
 [0.]]
(I ⊗ X)|10⟩ = Quantum object: dims=[[2, 2], [1]], shape=(4, 1), type='ket', dtype=Dense
Qobj data =
[[0.]
 [0.]
 [0.]
 [1.]]
(I ⊗ X)|11⟩ = Quantum object: dims=[[2, 2], [1]], shape=

## 3. The $H \otimes H$ Gate

### Mathematical Form

$$ H \otimes H = \frac{1}{2} \begin{pmatrix} 1 & 1 & 1 & 1 \\ 1 & -1 & 1 & -1 \\ 1 & 1 & -1 & -1 \\ 1 & -1 & -1 & 1 \end{pmatrix} $$

### Action on Basis States

<table style="width: 100%; border-collapse: collapse;">
    <thead>
        <tr>
            <th style="text-align: left; padding: 8px; background-color: #f2f2f2;">Input</th>
            <th style="text-align: left; padding: 8px; background-color: #f2f2f2;">Output</th>
            <th style="text-align: left; padding: 8px; background-color: #f2f2f2;">Explanation</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td style="padding: 8px;">$|00\rangle$</td>
            <td style="padding: 8px;">$\frac{1}{2}(|00\rangle + |01\rangle + |10\rangle + |11\rangle)$</td>
            <td style="padding: 8px;">$|+\rangle|+\rangle$</td>
        </tr>
        <tr>
            <td style="padding: 8px;">$|01\rangle$</td>
            <td style="padding: 8px;">$\frac{1}{2}(|00\rangle - |01\rangle + |10\rangle - |11\rangle)$</td>
            <td style="padding: 8px;">$|+\rangle|-\rangle$</td>
        </tr>
        <tr>
            <td style="padding: 8px;">$|10\rangle$</td>
            <td style="padding: 8px;">$\frac{1}{2}(|00\rangle + |01\rangle - |10\rangle - |11\rangle)$</td>
            <td style="padding: 8px;">$|-\rangle|+\rangle$</td>
        </tr>
        <tr>
            <td style="padding: 8px;">$|11\rangle$</td>
            <td style="padding: 8px;">$\frac{1}{2}(|00\rangle - |01\rangle - |10\rangle + |11\rangle)$</td>
            <td style="padding: 8px;">$|-\rangle|-\rangle$</td>
        </tr>
    </tbody>
</table>

### Key Insight

$H \otimes H$ creates a uniform superposition of all basis states, which is the starting point for many quantum algorithms (Deutsch-Jozsa, Grover, Shor).

In [4]:
# ============================================================================
# H ⊗ H GATE DEMONSTRATION
# ============================================================================

print("=" * 70)
print("H ⊗ H GATE DEMONSTRATION")
print("=" * 70)

# Define H ⊗ H
I = qt.qeye(2)
H = (1 / np.sqrt(2)) * (qt.sigmax() + qt.sigmaz())
H_H = qt.tensor(H, H)

print("\nH ⊗ H matrix:")
print(H_H)

# Create basis states
ket0 = qt.basis(2, 0)
ket1 = qt.basis(2, 1)

ket00 = qt.tensor(ket0, ket0)
ket01 = qt.tensor(ket0, ket1)
ket10 = qt.tensor(ket1, ket0)
ket11 = qt.tensor(ket1, ket1)

basis_states = [("|00⟩", ket00), ("|01⟩", ket01), ("|10⟩", ket10), ("|11⟩", ket11)]

print("\n" + "=" * 50)
print("H ⊗ H ACTIONS")
print("=" * 50)

for name, state in basis_states:
    result = H_H * state
    print(f"(H ⊗ H){name} = {result}")

# Verify that applying H ⊗ H twice returns to original state
print("\n" + "=" * 50)
print("H ⊗ H IS ITS OWN INVERSE")
print("=" * 50)

for name, state in basis_states:
    result = H_H * H_H * state
    is_original = np.allclose(result.full(), state.full())
    print(f"(H ⊗ H)²{name} = {name}? {is_original}")

print("\n✅ H ⊗ H is its own inverse!")

H ⊗ H GATE DEMONSTRATION

H ⊗ H matrix:
Quantum object: dims=[[2, 2], [2, 2]], shape=(4, 4), type='oper', dtype=CSR, isherm=True
Qobj data =
[[ 0.5  0.5  0.5  0.5]
 [ 0.5 -0.5  0.5 -0.5]
 [ 0.5  0.5 -0.5 -0.5]
 [ 0.5 -0.5 -0.5  0.5]]

H ⊗ H ACTIONS
(H ⊗ H)|00⟩ = Quantum object: dims=[[2, 2], [1]], shape=(4, 1), type='ket', dtype=Dense
Qobj data =
[[0.5]
 [0.5]
 [0.5]
 [0.5]]
(H ⊗ H)|01⟩ = Quantum object: dims=[[2, 2], [1]], shape=(4, 1), type='ket', dtype=Dense
Qobj data =
[[ 0.5]
 [-0.5]
 [ 0.5]
 [-0.5]]
(H ⊗ H)|10⟩ = Quantum object: dims=[[2, 2], [1]], shape=(4, 1), type='ket', dtype=Dense
Qobj data =
[[ 0.5]
 [ 0.5]
 [-0.5]
 [-0.5]]
(H ⊗ H)|11⟩ = Quantum object: dims=[[2, 2], [1]], shape=(4, 1), type='ket', dtype=Dense
Qobj data =
[[ 0.5]
 [-0.5]
 [-0.5]
 [ 0.5]]

H ⊗ H IS ITS OWN INVERSE
(H ⊗ H)²|00⟩ = |00⟩? True
(H ⊗ H)²|01⟩ = |01⟩? True
(H ⊗ H)²|10⟩ = |10⟩? True
(H ⊗ H)²|11⟩ = |11⟩? True

✅ H ⊗ H is its own inverse!


## 4. Applying Gates to Specific Qubits

### The Pattern

To apply a gate $U$ to qubit $i$ in an $n$-qubit system:

- Insert $I$ (identity) for all other qubits
- The order of tensor product follows qubit ordering

### For Two Qubits

<table style="width: 100%; border-collapse: collapse;">
    <thead>
        <tr>
            <th style="text-align: left; padding: 8px; background-color: #f2f2f2;">Desired Operation</th>
            <th style="text-align: left; padding: 8px; background-color: #f2f2f2;">Mathematical Form</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td style="padding: 8px;">Apply $X$ to qubit 0, $I$ to qubit 1</td>
            <td style="padding: 8px;">$X \otimes I$</td>
        </tr>
        <tr>
            <td style="padding: 8px;">Apply $I$ to qubit 0, $X$ to qubit 1</td>
            <td style="padding: 8px;">$I \otimes X$</td>
        </tr>
        <tr>
            <td style="padding: 8px;">Apply $H$ to qubit 0, $I$ to qubit 1</td>
            <td style="padding: 8px;">$H \otimes I$</td>
        </tr>
        <tr>
            <td style="padding: 8px;">Apply $I$ to qubit 0, $H$ to qubit 1</td>
            <td style="padding: 8px;">$I \otimes H$</td>
        </tr>
        <tr>
            <td style="padding: 8px;">Apply $Z$ to qubit 0, $X$ to qubit 1</td>
            <td style="padding: 8px;">$Z \otimes X$</td>
        </tr>
    </tbody>
</table>

### Important Observation

The order matters: $X \otimes I$ is different from $I \otimes X$.

- $X \otimes I$: Flips first qubit, leaves second unchanged
- $I \otimes X$: Leaves first unchanged, flips second qubit

### Matrix Representation Example

$$ X \otimes I = \begin{pmatrix} 0 & 0 & 1 & 0 \\ 0 & 0 & 0 & 1 \\ 1 & 0 & 0 & 0 \\ 0 & 1 & 0 & 0 \end{pmatrix} $$

$$ I \otimes X = \begin{pmatrix} 0 & 1 & 0 & 0 \\ 1 & 0 & 0 & 0 \\ 0 & 0 & 0 & 1 \\ 0 & 0 & 1 & 0 \end{pmatrix} $$

In [5]:
# ============================================================================
# APPLYING GATES TO SPECIFIC QUBITS
# ============================================================================

print("=" * 70)
print("APPLYING GATES TO SPECIFIC QUBITS")
print("=" * 70)

# Define gates
I = qt.qeye(2)
X = qt.sigmax()
H = (1 / np.sqrt(2)) * (qt.sigmax() + qt.sigmaz())
Z = qt.sigmaz()

# Different tensor product combinations
X_I = qt.tensor(X, I)        # X on qubit 0, I on qubit 1
I_X = qt.tensor(I, X)        # I on qubit 0, X on qubit 1
H_I = qt.tensor(H, I)        # H on qubit 0, I on qubit 1
I_H = qt.tensor(I, H)        # I on qubit 0, H on qubit 1
Z_X = qt.tensor(Z, X)        # Z on qubit 0, X on qubit 1

print("\nDifferent gate combinations:")
print(f"X ⊗ I =\n{X_I}")
print(f"\nI ⊗ X =\n{I_X}")
print(f"\nH ⊗ I =\n{H_I}")
print(f"\nI ⊗ H =\n{I_H}")
print(f"\nZ ⊗ X =\n{Z_X}")

# Create basis states
ket0 = qt.basis(2, 0)
ket1 = qt.basis(2, 1)
ket00 = qt.tensor(ket0, ket0)
ket01 = qt.tensor(ket0, ket1)
ket10 = qt.tensor(ket1, ket0)
ket11 = qt.tensor(ket1, ket1)

basis_states = [("|00⟩", ket00), ("|01⟩", ket01), ("|10⟩", ket10), ("|11⟩", ket11)]

# ============================================================================
# TEST X ⊗ I ON ALL BASIS STATES
# ============================================================================
print("\n" + "=" * 50)
print("TESTING X ⊗ I ON ALL BASIS STATES")
print("=" * 50)

for name, state in basis_states:
    result = X_I * state
    print(f"(X ⊗ I){name} = {result}")

# ============================================================================
# TEST I ⊗ X ON ALL BASIS STATES
# ============================================================================
print("\n" + "=" * 50)
print("TESTING I ⊗ X ON ALL BASIS STATES")
print("=" * 50)

for name, state in basis_states:
    result = I_X * state
    print(f"(I ⊗ X){name} = {result}")

# ============================================================================
# TEST H ⊗ I ON |00⟩
# ============================================================================
print("\n" + "=" * 50)
print("TESTING H ⊗ I ON |00⟩")
print("=" * 50)

result = H_I * ket00
print(f"(H ⊗ I)|00⟩ = {result}")
print(f"Expected: |+⟩|0⟩ = {qt.tensor((ket0 + ket1).unit(), ket0)}")

# ============================================================================
# TEST I ⊗ H ON |00⟩
# ============================================================================
print("\n" + "=" * 50)
print("TESTING I ⊗ H ON |00⟩")
print("=" * 50)

result = I_H * ket00
print(f"(I ⊗ H)|00⟩ = {result}")
print(f"Expected: |0⟩|+⟩ = {qt.tensor(ket0, (ket0 + ket1).unit())}")

# ============================================================================
# TEST Z ⊗ X ON |00⟩
# ============================================================================
print("\n" + "=" * 50)
print("TESTING Z ⊗ X ON |00⟩")
print("=" * 50)

result = Z_X * ket00
print(f"(Z ⊗ X)|00⟩ = {result}")
print(f"Expected: |01⟩ (Z on |0⟩ gives |0⟩, X on |0⟩ gives |1⟩) = {ket01}")

# ============================================================================
# VERIFY THAT X ⊗ I AND I ⊗ X ARE DIFFERENT
# ============================================================================
print("\n" + "=" * 50)
print("VERIFYING X ⊗ I ≠ I ⊗ X")
print("=" * 50)

are_equal = np.allclose(X_I.full(), I_X.full())
print(f"X ⊗ I == I ⊗ X? {are_equal}")
print("✅ They are different! Order matters in tensor products.")

APPLYING GATES TO SPECIFIC QUBITS

Different gate combinations:
X ⊗ I =
Quantum object: dims=[[2, 2], [2, 2]], shape=(4, 4), type='oper', dtype=CSR, isherm=True
Qobj data =
[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]

I ⊗ X =
Quantum object: dims=[[2, 2], [2, 2]], shape=(4, 4), type='oper', dtype=CSR, isherm=True
Qobj data =
[[0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]]

H ⊗ I =
Quantum object: dims=[[2, 2], [2, 2]], shape=(4, 4), type='oper', dtype=CSR, isherm=True
Qobj data =
[[ 0.70710678  0.          0.70710678  0.        ]
 [ 0.          0.70710678  0.          0.70710678]
 [ 0.70710678  0.         -0.70710678  0.        ]
 [ 0.          0.70710678  0.         -0.70710678]]

I ⊗ H =
Quantum object: dims=[[2, 2], [2, 2]], shape=(4, 4), type='oper', dtype=CSR, isherm=True
Qobj data =
[[ 0.70710678  0.70710678  0.          0.        ]
 [ 0.70710678 -0.70710678  0.          0.        ]
 [ 0.          0.          0.70710678  0.70710678]
 [ 0.          0.

## 5. Summary and Key Insights

### Tensor Product Gates Summary

<table style="width: 100%; border-collapse: collapse;">
    <thead>
        <tr>
            <th style="text-align: left; padding: 8px; background-color: #f2f2f2;">Gate</th>
            <th style="text-align: left; padding: 8px; background-color: #f2f2f2;">Matrix (4x4)</th>
            <th style="text-align: left; padding: 8px; background-color: #f2f2f2;">Action</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td style="padding: 8px;">$X \otimes I$</td>
            <td style="padding: 8px;">[[0,0,1,0],[0,0,0,1],[1,0,0,0],[0,1,0,0]]</td>
            <td style="padding: 8px;">Flips first qubit</td>
        </tr>
        <tr>
            <td style="padding: 8px;">$I \otimes X$</td>
            <td style="padding: 8px;">[[0,1,0,0],[1,0,0,0],[0,0,0,1],[0,0,1,0]]</td>
            <td style="padding: 8px;">Flips second qubit</td>
        </tr>
        <tr>
            <td style="padding: 8px;">$X \otimes X$</td>
            <td style="padding: 8px;">[[0,0,0,1],[0,0,1,0],[0,1,0,0],[1,0,0,0]]</td>
            <td style="padding: 8px;">Flips both qubits</td>
        </tr>
        <tr>
            <td style="padding: 8px;">$Z \otimes Z$</td>
            <td style="padding: 8px;">[[1,0,0,0],[0,-1,0,0],[0,0,-1,0],[0,0,0,1]]</td>
            <td style="padding: 8px;">Phase flip on $|01\rangle$ and $|10\rangle$</td>
        </tr>
        <tr>
            <td style="padding: 8px;">$H \otimes H$</td>
            <td style="padding: 8px;">(1/2)[[1,1,1,1],[1,-1,1,-1],[1,1,-1,-1],[1,-1,-1,1]]</td>
            <td style="padding: 8px;">Creates superposition on both qubits</td>
        </tr>
    </tbody>
</table>

### Key Formulas

$$ (A \otimes B)(|\psi\rangle \otimes |\phi\rangle) = (A|\psi\rangle) \otimes (B|\phi\rangle) $$

$$ A \otimes B = \begin{pmatrix} a_{11}B & a_{12}B \\ a_{21}B & a_{22}B \end{pmatrix} $$

### Key Takeaways

1. **Tensor products** combine single-qubit gates into multi-qubit gates
2. **$X \otimes I$ vs $I \otimes X$** shows that order matters
3. **$X \otimes X$** flips both qubits simultaneously
4. **$Z \otimes Z$** applies a phase based on parity (even/odd number of 1s)
5. **$H \otimes H$** creates uniform superposition across all basis states
6. **Single-qubit gates** on specific qubits use $I$ on others

---

**Day 10 Complete!** 🎉

You now understand:
- How to construct multi-qubit gates using tensor products
- The action of $X \otimes I$, $I \otimes X$, $X \otimes X$, $Z \otimes Z$, and $H \otimes H$
- How to apply gates to specific qubits
- The mathematical structure of composite gates

Proceed to Day 11 when ready.